{% set name = "jasper" %}
{% set version = "4.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jasper-software/jasper/releases/download/version-{{ version }}/jasper-{{ version }}.tar.gz
  sha256: 68131ddf9f62d6944cc4c58977dd177c283adb0228140b76382a2dbdadadaa4f

build:
  number: 0
  skip: true  # [s390x]
  run_exports:
    # no info.  Leaving at default behavior.
    - {{ pin_subpackage('jasper') }}
  missing_dso_whitelist:                                         # [osx or linux]
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT  # [osx]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libc.so.6  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libxdamage') }}           # [linux]
    - {{ cdt('libselinux') }}           # [linux]
    - {{ cdt('libxext') }}              # [linux]
    - {{ cdt('libxfixes') }}            # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxau') }}               # [linux]
    - {{ cdt('libxi') }}                # [linux]
    - {{ cdt('libxxf86vm') }}           # [linux]
    - cmake
    - ninja                             # [win]
    - make                              # [not win]
  host:
    - jpeg {{ jpeg }}
    - libglu 9.0.0                     # [linux]
    - freeglut 3.0.0                    # [linux or win]
  run:
    - jpeg # pin through run_exports
    - {{ pin_compatible('libglu') }}    # [linux]
    - {{ pin_compatible('freeglut') }}  # [linux or win]

test:
  commands:
    - if not exist %LIBRARY_BIN%\\jasper.dll exit 1  # [win]
    - jasper --version

about:
  home: https://www.ece.uvic.ca/~frodo/jasper/
  dev_url: https://github.com/jasper-software/jasper
  doc_url: https://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer-2.0
  license_family: Other
  license_file: LICENSE.txt
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
  description: |
    The JasPer Project is an open-source initiative to provide
    a free software-based reference implementation of the codec specified
    in the JPEG-2000 Part-1 standard (i.e., ISO/IEC 15444-1).

extra:
  recipe-maintainers:
    - jakirkham
    - jhamman
    - ocefpaf
