{% set name = "jasper" %}
{% set version = "4.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://ftp2.osuosl.org/pub/blfs/conglomeration/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1263d70c663f1b5a4ed2a428371486091d282af96b7270e8b1cbfcbf44ad95ff

build:
  number: 0
  skip: true  # [s390x]
  run_exports:
    # no info.  Leaving at default behavior.
    - {{ pin_subpackage('jasper') }}
  missing_dso_whitelist:                                         # [osx or linux]
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT  # [osx]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libc.so.6  # [linux]
  ignore_run_exports:
    - jpeg

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libxdamage') }}           # [linux]
    - {{ cdt('libselinux') }}           # [linux]
    - {{ cdt('libxext') }}              # [linux]
    - {{ cdt('libxfixes') }}            # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxau') }}               # [linux]
    - {{ cdt('libxi') }}                # [linux]
    - {{ cdt('libxxf86vm') }}           # [linux]
    - cmake
    - ninja                             # [win]
    - make                              # [not win]
    - patch                             # [not win]
    - m2-patch                          # [win]
  host:
    - jpeg
    - libglu                            # [linux]
    - freeglut                          # [linux or win]
  run:
    - jpeg
    - {{ pin_compatible('libglu') }}    # [linux]
    - {{ pin_compatible('freeglut') }}  # [linux or win]

test:
  commands:
    - if not exist %LIBRARY_BIN%\\jasper.dll exit 1  # [win]
    - jasper --version

about:
  home: https://www.ece.uvic.ca/~frodo/jasper/
  dev_url: https://github.com/jasper-software/jasper
  doc_url: https://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer-2.0
  license_file: LICENSE.txt
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
  description: |
    The JasPer Project is an open-source initiative to provide
    a free software-based reference implementation of the codec specified
    in the JPEG-2000 Part-1 standard (i.e., ISO/IEC 15444-1).

extra:
  recipe-maintainers:
    - jakirkham
    - jhamman
    - ocefpaf
