{% set name = "jasper" %}
{% set version = "4.2.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jasper-software/{{ name }}/releases/download/version-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98058a94fbff57ec6e31dcaec37290589de0ba6f47c966f92654681a56c71fae

build:
  number: 0
  run_exports:
    # no info.  Leaving at default behavior.
    - {{ pin_subpackage('jasper') }}
  missing_dso_whitelist:                                         # [osx]
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT  # [osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake
    - ninja-base
    - pkg-config
  host:
    - jpeg {{ jpeg }}
    - libglu {{ libglu }}               # [linux]
    - freeglut {{ freeglut }}           # [linux or win]
    # libgl-devel is needed for jiv to run on linux. 
    - libgl-devel {{ libgl }}           # [linux]
  run:
    - jpeg  # pin through run_exports
    - {{ pin_compatible('libglu') }}    # [linux]
    - {{ pin_compatible('freeglut') }}  # [linux or win]

test:
  commands:
    - if not exist %LIBRARY_BIN%\\jasper.dll exit 1            # [win]
    - if not exist %LIBRARY_BIN%\\jasper.exe exit 1            # [win]
    - if not exist %LIBRARY_BIN%\\jiv.exe exit 1               # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\jasper.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\jasper.lib exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\glut.lib exit 1              # [win]
    - if not exist %LIBRARY_INC%\\jasper\\jasper.h exit 1      # [win]
    - test -f $PREFIX/include/jasper/jasper.h                  # [unix]
    - test -f $PREFIX/lib/libjasper.dylib                      # [osx]
    - test -f $PREFIX/lib/libjasper.7.dylib                    # [osx]
    - test -f $PREFIX/lib/libjasper.7.0.0.dylib                # [osx]
    - test -f $PREFIX/lib/libjasper.so                         # [linux]
    - test -f $PREFIX/lib/libjasper.so.7                       # [linux]
    - test -f $PREFIX/lib/libjasper.so.7.0.0                   # [linux]
    - jasper --version
    # Skip running jiv on linux platforms because freeglut fails to open display
    - test -f $PREFIX/bin/jiv                                  # [linux]
    - jiv --version                                            # [win]

about:
  home: https://www.ece.uvic.ca/~frodo/jasper
  license: JasPer-2.0
  license_family: Other
  license_file: LICENSE.txt
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
  description: |
    The JasPer Project is an open-source initiative to provide
    a free software-based reference implementation of the codec specified
    in the JPEG-2000 Part-1 standard (i.e., ISO/IEC 15444-1).
  dev_url: https://github.com/jasper-software/jasper
  doc_url: https://jasper-software.github.io/jasper-manual/latest/html/index.html

extra:
  recipe-maintainers:
    - jakirkham
    - jhamman
    - ocefpaf
