travis:
  secure:
    BINSTAR_TOKEN: swDmdZyerFdw+8u6O42DnMDBdNQXr9By9DJYxFEWW8ROgBgcz6X/ORqVUDzpuF9QMkeRZRxKTCESVT2nefr5mt9mdKna7snQEbaDyML4KyW+uUopl6BWQLGkV3+ZGXkuXOJcnJOBTtzOBHP1evQNBoI/ZSPEF8kqe4HewX1dCZDahlGwe9P7ErTj98d4rYAB5+3B+exAikkzHDQ5QDAOa9UuYuJbXCGutqq96m6laMNue7vetCKPaI7aLRtGca6u9Bzrr4cNZbgFGsp2WDgZqflslehaze/olBN8zQjmaI7ZpSQ58vlSR1JEJzqT14tlrxUDyxo29E4W7Uc+r6/m/Yh7ZGRGsKaJHxg5Ay0+P9X2fPLcihwQWL23K79OFDOsUPH+FuXIfUPnpqVQ9ytXs6XuCHRuaFsElpYE2Vr+f0ocFIERnuOsfxqlS1mkt5ypCLnVjuwQ1nt6J2CLpOtLwZ7hnfvkcsk3wtS/3dUfT5W2Cyj9cE7HnSs6JXHnyl+xAStbXbkLKuUFAXW+/7NP8T67MwCoag4XMijmbzolrqjKBJGTjaFnhCJ2WqbU3uJcpgaMaIXkBqMJPW24sSHIm5K5hmys7j4ytacD70KboQKXqmDF+6CnZVdVJIQtjEfExHfQf+jI8tlcRusO/L2CZkLrUS6D7mLMv3oM5kQjrrs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
